name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          python -m pip install -e .
      - name: Build Documentation
        run: |
          cd docs
          make html
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./docs/build/html

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SAST
        uses: github/codeql-action/analyze@v1
        with:
          languages: python
          # include any additional queries you want to run
          # for example: - 'python/general/suspicious-malloc-usage.ql'
          queries: |
            - 'python/codeql-py-security-extended.qls'
          # set the path to your code
          # for example: 'src/**'
          search-path: '.'
        env:
          # set your CodeQL Analysis key
          # for more information see https://docs.github.com/en/code-security/codeql/automating-code-scanning-with-github-actions/codeql-bundle-locations-for-github-hosted-runners#using-automatically-generated-keys
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deployment:
    runs-on: ubuntu-latest
    needs: [documentation, security]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Deploy Application
        run: |
          echo "Deploying application..."
          docker-compose down
          docker image prune -f
          docker container prune -f
          docker-compose up -d --build
