name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          python -m venv aws
          source aws/bin/activate
          python -m pip install -e .
          python -m pip install -e .[doc]
      - name: Build Documentation
        run: |
          cd docs
          make html
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /docs/build/html # The folder the action should deploy.

  

  deployment:
    runs-on: ubuntu-latest
    needs: [documentation]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Deploy Application
        run: |
          echo "Deploying application..."
          docker-compose down
          docker image prune -f
          docker container prune -f
          docker-compose up -d --build
